In [1]:
document = ['The', 'cat', 'sat', 'on', 'the', 'mat']

In [2]:
vocab = {"The": 0, "cat": 1, "sat": 2, "on": 3, "the": 4, "mat": 5}
tokenized_document = [vocab[word] for word in document]

In [5]:
import torch
import torch.nn as nn

document = ["The", "cat", "sat", "on", "the", "mat"]
vocab = {"The": 0, "cat": 1, "sat": 2, "on": 3, "the": 4, "mat": 5}

# Convert words to indices
tokenized_document = [vocab[word] for word in document]


In [6]:
tokenized_document

[0, 1, 2, 3, 4, 5]

In [10]:
# Step 2: Define the embedding layer
vocab_size = len(vocab)
embedding_dim = 8 # Dimension of the embeddings
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim= embedding_dim)

print("Total vocab length: ",vocab_size)
print("embeding dimention: ",embedding_layer)

Total vocab length:  6
embeding dimention:  Embedding(6, 8)


In [13]:
# Convert tokenized document to a tensor:
tokenized_document_tensor=torch.tensor(tokenized_document, dtype=torch.long)
tokenized_document_tensor

tensor([0, 1, 2, 3, 4, 5])

In [15]:
# Step 3: Pass the tokenized document through the embedding layer
embedded_document = embedding_layer(tokenized_document_tensor)
embedded_document

tensor([[ 0.4852, -1.2485,  0.0559,  1.3282, -0.1493, -0.1792, -0.4834,  0.8161],
        [-0.8813, -1.0965, -0.7389,  0.8518, -0.3262,  1.4533, -0.4729,  1.5557],
        [-0.3882, -1.1924, -1.7779,  0.5747, -1.6086, -0.8626,  0.9148,  0.4478],
        [-0.9386, -1.1601,  1.7668, -0.4469, -0.5911, -0.9946,  0.4276,  0.2412],
        [-0.4059, -0.5693,  0.6429, -1.1780,  1.9843,  0.5548, -0.3797,  0.0209],
        [-0.8943, -0.1529, -0.2080, -0.0604, -1.7326,  0.1557,  0.7743,  0.5963]],
       grad_fn=<EmbeddingBackward0>)

In [16]:
# Print the embbed document
print("Tokenized Document: ", tokenized_document)
print("Embedded Document:\n", embedded_document)

Tokenized Document:  [0, 1, 2, 3, 4, 5]
Embedded Document:
 tensor([[ 0.4852, -1.2485,  0.0559,  1.3282, -0.1493, -0.1792, -0.4834,  0.8161],
        [-0.8813, -1.0965, -0.7389,  0.8518, -0.3262,  1.4533, -0.4729,  1.5557],
        [-0.3882, -1.1924, -1.7779,  0.5747, -1.6086, -0.8626,  0.9148,  0.4478],
        [-0.9386, -1.1601,  1.7668, -0.4469, -0.5911, -0.9946,  0.4276,  0.2412],
        [-0.4059, -0.5693,  0.6429, -1.1780,  1.9843,  0.5548, -0.3797,  0.0209],
        [-0.8943, -0.1529, -0.2080, -0.0604, -1.7326,  0.1557,  0.7743,  0.5963]],
       grad_fn=<EmbeddingBackward0>)


### Explanation
__1. Vocabulary Creation:__ We manually create a vocabulary that maps each unique word to an index.

__2. Tokenization:__ We convert each word in the document to its corresponding index based on the vocabulary.

__3. Embedding Layer:__ We define an nn.Embedding layer with the vocabulary size and the desired embedding dimension. This layer is trainable and will learn embeddings during training if integrated into a larger model.

__4. Tensor Conversion:__ We convert the tokenized document into a PyTorch tensor.

__5. Generate Embeddings:__ We pass the tokenized tensor through the embedding layer to obtain the embeddings.


### Next Steps
After generating embeddings for a document, the next steps typically involve integrating these embeddings into a more complex model like a Transformer encoder or decoder. If you want to proceed with creating other components of the Transformer model, let me know which part you'd like to tackle next!